# Generated by Django 4.0.3 on 2022-06-03 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngo', '0003_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Evente',
        ),
    ]
