# Generated by Django 4.0.3 on 2022-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_rename_events_evente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evente',
            name='eventdate',
            field=models.DateField(null=True),
        ),
    ]
