# Generated by Django 4.0.5 on 2022-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_volunteer_project_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
