# Generated by Django 4.0.5 on 2022-06-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0007_volunteer_email_volunteer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngo.project'),
        ),
    ]
